baseURL = 'https://danielraj.com/'
languageCode = 'en-us'
title = 'Daniel Raj'
theme = 'PaperMod'

[params.profileMode]
enabled = true
title = "hi, i'm daniel"
subtitle = "I love coding and building websites."


[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/frorevale/"

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/FroreVale"

[[params.socialIcons]]
name = "Email"
url = "mailto:danielraj1159@gmail.com"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
